/*DROP TABLE IF EXISTS FILM;

CREATE TABLE FILM (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  annee VARCHAR(250) NOT NULL,
  realisateur VARCHAR(250) NOT NULL,
  genre VARCHAR(250) NOT NULL,
  emplacement VARCHAR(250) NOT NULL
);*/
